# NumPy 정리

Creating Arrays from Python Lists

In [4]:
import numpy as np

np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 4, 2, 3]) 
# 소수와 정수가 섞이면 모두 소수화 됨

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
# array 유형을 지정하고싶으면 
np.array([3, 4, 2, 3], dtype = 'float32')

array([3., 4., 2., 3.], dtype=float32)

In [9]:
# unlike Python lists, NumPy arrays can explicitly be multidimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# 10개의 0으로 구성된 array
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# 1로 구성된 3x5 array
np.ones((3,5), dtype= float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# 3.14로 구성된 3x5 array
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# 0부터 19까지의 수를 2칸씩 건너뛰면서
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# 0~1사이를 5개로 균등하게 나누기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Create a 3x3 array of uniformly distributed
np.random.random((3,3))

array([[0.94178825, 0.04602521, 0.07195412],
       [0.00885588, 0.54368414, 0.52671432],
       [0.25086889, 0.27104821, 0.51829132]])

In [23]:
# Create a 3x3 array of normally distributed random values
# mean 0 and sd 1
np.random.normal(0,1,(3,3))

array([[-0.90401418, -0.96105474,  0.17239072],
       [ 1.40510467,  1.058598  , -0.29828749],
       [-0.93970647, -1.18589592, -0.5480245 ]])

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[4, 7, 4],
       [9, 1, 3],
       [5, 0, 0]])

### numpy array attributes

In [25]:
np.random.seed(0)

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array # 4x5를 총 3개

In [29]:
print(x3.ndim, x3.shape, x3.size)

3 (3, 4, 5) 60


In [30]:
print(x3.dtype)

int32


In [31]:
print(x3.itemsize, x3.nbytes)

4 240


### Array Indexing: Accessing Single Elements

In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0]

5

In [35]:
x1[4]

7

In [39]:
x1[-1] # 끝에서 첫번째

9

In [40]:
x1[-2] # 끝에서 두번째

7

In [41]:
# multidimensional array의 경우
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [42]:
x2[0,0]

3

In [43]:
x2[2,0]

1

In [44]:
x2[2,-1]

7

In [46]:
# modify values
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

** 주의할점!!
numpy는 고정된 타입을 가지므로 integer array에다가 floating point value를
넣으면 integer로 바뀜

In [48]:
x1[0] = 3.1456
x1
# 3.1456이 아닌 정수3으로 바뀌게 됨

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays
x[start:stop:step]

#### one-dimensional subarrays

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x[:5] # 첫번째 다섯개 element (5번째도 포함)

array([0, 1, 2, 3, 4])

In [54]:
x[4:] # 4번째 부터의  (4번째도 포함)

array([4, 5, 6, 7, 8, 9])

In [56]:
x[4:7] # 4번째부터 6번째 까지 (7번째는 포함X)

array([4, 5, 6])

In [57]:
x[::2] # 처음부터 끝까지 2칸씩 추출

array([0, 2, 4, 6, 8])

In [58]:
x[1::2] # 첫번째 부터 끝까지 2칸씩 추출

array([1, 3, 5, 7, 9])

In [59]:
# step value가 음수인 경우
x[::-1] # array를 reverse할때

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
x[5::-2]
# 5번째부터 거꾸로 2개씩 추출

array([5, 3, 1])

#### Multidimensional subarrays

In [63]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [64]:
x2[:2,:3] # 두번째행, 세번째 열까지

array([[12,  5,  2],
       [ 7,  6,  8]])

In [66]:
x2[:3, ::2] # 세번째 행까지, 열은 처음부터 끝까지 두칸씩 건너뛰어

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [67]:
x2[::-1,::-1] # 행,열 모두 순서 바꾸기 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [68]:
x2[:, 0] # 첫번째 열

array([12,  7,  1])

In [69]:
x2[0,:] # 첫번째 행
x[0] # 동일한 결과

0

** 주의할점!!!
#### Subarrays as no-copy views
subarray의 element를 바꾸면 원래 array의 element도 바뀌어버림!!!
copies가 아닌 view이기 때문.. **<- python list와 다른점**

In [70]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [71]:
# extract 2x2 subarray
x2_sub = x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [73]:
# 이 subarray를 수정하면 original array도 변경됨
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [74]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [75]:
# Creating copies of arrays
x2_sub_copy = x2[:2,:2].copy()

In [76]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [78]:
print(x2)
# 즉 subarray를 copy한 것의 element를 수정하면 원래 array에 영향을 미치지 않음

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays
reshape()을 통해

In [80]:
#  put the numbers 1 through 9 in a 3×3 grid
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Another common reshaping pattern is the conversion of a one-dimensional array
into a two-dimensional row or column matrix. You can do this with the reshape
method, or more easily by making use of the newaxis keyword within a slice opera‐
tion

In [81]:
x = np.array([1, 2, 3])

In [82]:
x.reshape((1,3)) # reshape을 통해 row vector로

array([[1, 2, 3]])

In [83]:
x[np.newaxis, :] # 똑같은 결과

array([[1, 2, 3]])

In [84]:
x.reshape((3,1)) # reshape을 통해 column vector로

array([[1],
       [2],
       [3]])

In [85]:
x[:, np.newaxis] # 똑같은 결과

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting
combine
multiple arrays into one, and to conversely split a single array into multiple arrays.


In [86]:
# Concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [87]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [89]:
# For two-dimensional arrays:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid,grid]) # 기본은 밑으로 붙이기

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [90]:
np.concatenate([grid,grid], axis = 1) # 옆으로 붙이기

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [92]:
# For working with arrays of mixed dimensions, 
# use the np.vstack (vertical stack) and np.hstack (horizontal stack) 

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid]) # vertically. 즉 밑으로 쌓기

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [93]:
y = np.array([[99],
              [99]])
np.hstack([grid, y]) # horizontally. 즉 옆으로 쌓기

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [96]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
# [,]는 split points. 3번째와 5번째에서 쪼개라.

print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [97]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [100]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### numpy 연산

In [101]:
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [2]:
# 기초통계량 계산
import numpy as np

np.random.seed(13)
x = np.random.randint(10, size=(3,4))
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [3]:
print(np.sum(x))           # 원소의 총 합계
print(np.min(x, axis=1))   # 각 행의 최소값
print(np.mean(x, axis=0))  # 각 열의 평균
print(np.std(x, axis=0))   # 각 열의 표준편차
# axis가 0이면 열, 1이면 행

43
[0 2 2]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [4]:
x = np.array([[1,2,3,10], [5,6,7,8]]); print(x)

[[ 1  2  3 10]
 [ 5  6  7  8]]


In [5]:
print(x >= 5) # true나 false로 반환
print(np.sum(x>=5)) # x가 5보다 큰것의 개수를 합해줌 (true면 1 false면 0) # x>=5 자체가 논리식이므로 true나 false
print(np.sum(x>=5, axis=1))  # 각 행별로 5보다 큰 것의 개수

[[False False False  True]
 [ True  True  True  True]]
5
[1 4]


In [6]:
print(np.any(x>100))   # 100보다 큰 숫자가 있는지 없는지 판단할때
print(np.all(x<7, axis=0))   # 각 열별로 연산
print(np.all(x==100)) # 모두 100이냐?

False
[ True  True False False]
False


In [7]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) ; print(x)
y = np.array([1,0,1,0]) ; print(y)
print(x[y==0, :])  # y=0인 행(1,3행) 과 모든 열 
print('---------------------------')
print(x[:, y==0])  # 모든 행과 y=0인 열(1,3행)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 0 1 0]
[[ 5  6  7  8]
 [13 14 15 16]]
---------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [9]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99]) 
ind1 = np.array([2, 3, 8])
ind2 = np.array([[2,1,3], [5,2,7]])

x1 = x[ind1] # [2,3,8]번째 행만 추출
x2 = x[ind2] # 첫번째 행은 [2,1,3]번째 꺼 / 두번째 행은 [5,2,7]번째 꺼 

print(x1)
print('---------------------------')
print(x2)

[33 44 99]
---------------------------
[[33 22 44]
 [66 33 88]]


### Computation on Arrays: Broadcasting
Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on **arrays of different sizes**

Recall that for arrays of the same size, binary operations are performed on an
element-by-element basis:

In [10]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [11]:
a + 5

array([5, 6, 7])

In [13]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Here the one-dimensional array a is stretched, or broadcast, across the second
dimension in order to match the shape of M

In [16]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a); print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [17]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

we’ve stretched both a and b to match a common shape,
and the result is a twodimensional array

In [19]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]
# 차례대로 X[0,2] / X[1,1] / X[2,3] 을 인덱싱

array([ 2,  5, 11])

In [24]:
x = np.arange(12).reshape((3,4)) # np.arange(12)는 0~11까지의 벡터를 만든것.
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print(x[y1, y2]) 
# 차례대로 X[1,2] / X[2,0] / X[2,1] 을 인덱싱

[6 8 9]


In [26]:
y1[:,np.newaxis]

array([[1],
       [2],
       [2]])

In [29]:
x[y1[:,np.newaxis], y2]  # 이게 이해가 안감....

array([[ 6,  4,  5],
       [10,  8,  9],
       [10,  8,  9]])

In [30]:
x = np.array([2, 4, 3, 1, 5])
print(np.sort(x))

[1 2 3 4 5]


In [31]:
ind = np.argsort(x) # sort한 것의 index
print(ind) 

[3 0 2 1 4]
