In [ ]:
# =============================================================================
# =========================== 7.판다스(Pandas) ================================
# =============================================================================

In [1]:
import pandas as pd   #판다스 Pakage를 불러오는 명령어
X1=pd.Series([0.1,0.2,0.3,0.4], index=['a','b','c','d'])  #행렬에 index를 부여할 수 있다. numpy와 다른점.
print(X1); 

a    0.1
b    0.2
c    0.3
d    0.4
dtype: float64


In [2]:
print(X1.index)   #Series의 인덱스 
print(X1.values)  #Series의 value

Index(['a', 'b', 'c', 'd'], dtype='object')
[0.1 0.2 0.3 0.4]


In [3]:
print(X1['a':'c'])   #자료의 Slicing   1.index가 a~c까지
print(X1[0:3])       #자료의 Slicing   2.0~2행 까지

a    0.1
b    0.2
c    0.3
dtype: float64
a    0.1
b    0.2
c    0.3
dtype: float64


In [5]:
# ###########Series와 DataFrame#######

#Dictionary 형식 데이터를 1차원 자료로 환원
population1={'서울':9700000,
             '부산':4500000,
             '인천':4000000,
             '광주':2000000,
             '대구':2500000}
popu=pd.Series(population1)
print(popu)      #dictionary 형식 데이터에서 key가 Series의 index로 변한

서울    9700000
부산    4500000
인천    4000000
광주    2000000
대구    2500000
dtype: int64


In [6]:
#행 이름과 열이름의 부여
X2=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'],index=[1,2,3])
print(X2)

   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9


In [8]:
#앞의 예제에서 population에 열이름에 'pop'를 붙임.
pd.DataFrame(popu,columns=['pop'])

# 1차원 array-->  2차원 행렬자료
#열 벡터의 열 이름을 부여할 수 있음.

pop
서울  9700000
부산  4500000
인천  4000000
광주  2000000
대구  2500000

In [9]:
ind1={'서울':95,
     '부산':80,
     '인천':85,
     '광주':75,
     '대구':80}
print(ind1)

{'서울': 95, '부산': 80, '인천': 85, '광주': 75, '대구': 80}


In [10]:
#Series 로 변환
ind=pd.Series(ind1)
print(ind)

서울    95
부산    80
인천    85
광주    75
대구    80
dtype: int64


In [12]:
#지역 이름을 index로 하는 DataFrame 생성
y=pd.DataFrame({'pop':popu,'자립도(%)':ind})
print(y)

        pop  자립도(%)
서울  9700000      95
부산  4500000      80
인천  4000000      85
광주  2000000      75
대구  2500000      80


In [14]:
#자료의 편집(Slicing)
print(y['자립도(%)'])  #열의 이름을 그대로 사용

서울    95
부산    80
인천    85
광주    75
대구    80
Name: 자립도(%), dtype: int64
        pop  자립도(%)
부산  4500000      80
인천  4000000      85
광주  2000000      75


In [ ]:
#자료의 편진(Slicing)
print(y['부산':'광주']) #index를 기준으로한 Sclicing

In [15]:
#pd.DataFrame의 편집(Slicing)은 Numpy의 Slicing도 사용가능.

import numpy as np #Nunpy Pakage를 불러오는 명령어
W=pd.DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d']) #예제 data의 생성
print(W)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [17]:
## data Slicing1: loc
print(W.loc[0:1,:]) #0행~1행까지의 자료를 Slicing : [a:b]는 a에서 b자리수 까지를 의미

   a  b  c  d
0  0  1  2  3
1  4  5  6  7


In [18]:
## data Slicing1: iloc
print(W.iloc[0:1,:])   #0행 자료를 Slicing  :[a:b]는 a에서 b-1 자리수 까지를 의미

# loc vs iloc

   a  b  c  d
0  0  1  2  3


In [19]:
# 서로 다른 차원의 합
D1=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
print(D1)

   a  b
0  1  2
1  3  4


In [20]:
D2=pd.DataFrame([[11,22,33],[44,55,66],[77,88,99]],columns=['a','b','c'])
print(D2)

    a   b   c
0  11  22  33
1  44  55  66
2  77  88  99


In [21]:
print(D1+D2)  #연산은 두 개의 자료 size가 다르더라도 error 메시지 없이 실행된다는 점에서 매우 유용한 기능

      a     b   c
0  12.0  24.0 NaN
1  47.0  59.0 NaN
2   NaN   NaN NaN


In [22]:
#실습요망
#D1-D2, D1/D2, D1*D2, D2*D1, D2%X1 도       D1+D2와 동일

In [ ]:
############7.1 결측 자료의 처리#############

In [23]:
N=pd.Series([1,np.nan,'missing',None])
N.isnull() # missing이면 True의 논리형 자료를 출력

0    False
1     True
2    False
3     True
dtype: bool

In [24]:
N[N.notnull()] #결측이 없는 자료만 추출

0          1
2    missing
dtype: object

In [25]:
N.fillna(0) #특정 숫자로 NaN을 대체하고 싶을 경우

0          1
1          0
2    missing
3          0
dtype: object

In [26]:
############7.1 결측 자료의 처리 계속  #############
M=pd.DataFrame([[1,None,2,None],[4,5,6,None],[None,7,8,None]],index=list('123'),columns=list('abcd')) #새로운 데이터의 정의
print(M)

     a    b  c     d
1  1.0  NaN  2  None
2  4.0  5.0  6  None
3  NaN  7.0  8  None


In [27]:
print(M.dropna(axis='columns',how='all')) #열을 기준으로 모두 NaN이면 열을 제거

     a    b  c
1  1.0  NaN  2
2  4.0  5.0  6
3  NaN  7.0  8


In [28]:
print(M.dropna(axis='rows',thresh=3)) #3개이상의 non-missing인 행만 남김.

     a    b  c     d
2  4.0  5.0  6  None


In [ ]:
print(M.fillna(method='bfill',axis=1)) #각 행별로(axis=1 이므로 across columns의 의미이다.) NaN의 바로 뒤 열값으로 채움

In [ ]:
print(M.fillna(method='ffill',axis=1)) #각 행별로 NaN의 바로 전 열의 값으로 결측치를 채움.

In [ ]:
#############7.2  논리적 인덱스#############

In [29]:
x=pd.DataFrame([[1,None,2,None],[3,4,5,None],[None,6,7,None]],index=list('123'),columns=list('abcd')) #새로운 데이터의 정의
print(x)

     a    b  c     d
1  1.0  NaN  2  None
2  3.0  4.0  5  None
3  NaN  6.0  7  None


In [30]:
x.loc['2','d']=99  #원소만 값을 변경
print(x)

     a    b  c     d
1  1.0  NaN  2  None
2  3.0  4.0  5    99
3  NaN  6.0  7  None


In [31]:
print(x[pd.isnull(x['b'])]) #조건문을 만족하는 행을 출력

     a   b  c     d
1  1.0 NaN  2  None


In [33]:
x[pd.isnull(x).any(axis=1)]['b'] #x의 각행에서 하나라도 결측치가 있는 행에서   'b'열의 값을 출력

1    NaN
3    6.0
Name: b, dtype: float64

In [32]:
x.loc[pd.isnull(x).any(axis=1),'b'] #위와 동일한 결과

1    NaN
3    6.0
Name: b, dtype: float64

In [34]:
x[pd.isnull(x).any(axis=1),'b']  # Error 발생

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [35]:
K=pd.DataFrame(np.arange(12).reshape(3, 4),columns=list('abcd'))  # 새로운 data의 정의
print(K)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [36]:
print(K.loc[K['b']>4]['c']) #b’열이 4보다 큰 행(두번째와 세 번째행)을 대상으로 ‘c’열의 값

1     6
2    10
Name: c, dtype: int32


In [37]:
print(K.loc[K['b']>4,'c']) #위와 동일한 결과

1     6
2    10
Name: c, dtype: int32


In [42]:
print(K.loc[K['b']>4,['b','d']]) #b’열이 4보다 큰 행(두번째와 세 번째행)을 대상으로 ‘c’,'d'열의 값

   b   d
1  5   7
2  9  11


In [43]:
P=pd.DataFrame(np.arange(6).reshape(2, 3),index=list('ab'),columns=list('123'))  #새로운 data의 설정
print(P)

   1  2  3
a  0  1  2
b  3  4  5


In [45]:
print(P.stack()) #행 index와 열 index를 만들어 자료를 재정리

a  1    0
   2    1
   3    2
b  1    3
   2    4
   3    5
dtype: int32


In [46]:
print(P.stack().unstack())  #위 과정의 반대방향.

   1  2  3
a  0  1  2
b  3  4  5


In [ ]:
###############7.3 Data 붙이기#################


In [47]:
Q1=pd.DataFrame([[1,2,3],[4,5,6]],columns=list('abc'))           #새로운 data의 생성
Q2=pd.DataFrame([[11,22,33],[44,55,66]],columns=list('bcd'))
print(Q1)
print('-------------------------')
print(Q2)

   a  b  c
0  1  2  3
1  4  5  6
-------------------------
    b   c   d
0  11  22  33
1  44  55  66


In [48]:
#밑으로 붙이기.
print(pd.concat([Q1,Q2]))                   #밑으로 붙이기
print('-------------------------')
print(pd.concat([Q1,Q2],ignore_index=True))  #순서있는 인덱스를 원할 경우
print('-------------------------')
print(pd.concat([Q1,Q2],join='inner'))      #공통으로 가지고 있는 열 ‘b’와 ‘c’로만 구성된 자료의 아래로 붙이기

     a   b   c     d
0  1.0   2   3   NaN
1  4.0   5   6   NaN
0  NaN  11  22  33.0
1  NaN  44  55  66.0
-------------------------
     a   b   c     d
0  1.0   2   3   NaN
1  4.0   5   6   NaN
2  NaN  11  22  33.0
3  NaN  44  55  66.0
-------------------------
    b   c
0   2   3
1   5   6
0  11  22
1  44  55


C:\Anaconda3\envs\py36_32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.
C:\Anaconda3\envs\py36_32\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  This is separate from the ipykernel package so we can avoid doing imports until


In [49]:
#옆으로 붙이기.
R1=pd.DataFrame([[1,2,3],[4,5,6]],columns=list('abc'))
R2=pd.DataFrame([[11,22],[33,44]],columns=list('de'))
print(R1)
print(R2)
print('-------------------------')
R3=pd.concat([R1,R2],axis=1)         # 옆으로 붙이기 :axis=1추가
print(R3)

   a  b  c
0  1  2  3
1  4  5  6
    d   e
0  11  22
1  33  44
-------------------------
   a  b  c   d   e
0  1  2  3  11  22
1  4  5  6  33  44


In [50]:
#공통된 열이 있을때의 옆으로 붙이기.
S1=pd.DataFrame([[1,'aa',3],[4,'bb',5]],columns=list('abc')) #새로운 data의 생성
S2=pd.DataFrame([[11,'bb'],[22,'aa']],columns=list('db'))
print(S1)
print(S2)
print('-------------------------')
S3=pd.merge(S1,S2,on='b') #'b'열을 기준으로 옆으로 붙이기.
print(S3) 

   a   b  c
0  1  aa  3
1  4  bb  5
    d   b
0  11  bb
1  22  aa
-------------------------
   a   b  c   d
0  1  aa  3  22
1  4  bb  5  11


In [51]:
#공통된 열이 있을때의 옆으로 붙이기.:공통 열에 반복이 있는 경우.
S11=pd.DataFrame([[1,'aa',3],[4,'bb',5],[6,'aa',7]],columns=list('abc'))
S21=pd.DataFrame([[11,'bb'],[22,'aa'],[33,'bb']],columns=list('db'))
print(S11)
print(S21)
print('-------------------------')
S31=pd.merge(S11,S21,on='b')
print(S31)

   a   b  c
0  1  aa  3
1  4  bb  5
2  6  aa  7
    d   b
0  11  bb
1  22  aa
2  33  bb
-------------------------
   a   b  c   d
0  1  aa  3  22
1  6  aa  7  22
2  4  bb  5  11
3  4  bb  5  33


In [52]:
#공통된 열이 있을때의 옆으로 붙이기.: 공통 열 이외의 열에 반복이 있는 경우.
S12=pd.DataFrame([['aa',3],['bb',5],['aa',7]],columns=list('ab'))
S22=pd.DataFrame([[11,'bb'],[22,'aa']],columns=list('ba'))
print(S12)
print(S22)
print('=========================')
S32=pd.merge(S12,S22,on='a')
print(S32)c

    a  b
0  aa  3
1  bb  5
2  aa  7
    b   a
0  11  bb
1  22  aa
    a  b_x  b_y
0  aa    3   22
1  aa    7   22
2  bb    5   11


In [54]:
#공통된 열이 있을때의 옆으로 붙이기.: 공통 열의 이름이 다른 경우 
U1=pd.DataFrame([[1,'aa',3],[4,'bb',5]],columns=list('abc'))
U2=pd.DataFrame([[11,'bb'],[22,'aa']],columns=list('de'))
print(U1)
print(U2)
print('-------------------------')
U3=pd.merge(U1,U2,left_on='b',right_on='e')
print(U3)
print('-------------------------')
U4=pd.merge(U1,U2,left_on='b',right_on='e').drop('e',axis=1)  #공통 열중 'e'열의 제거
print(U4)

   a   b  c
0  1  aa  3
1  4  bb  5
    d   e
0  11  bb
1  22  aa
-------------------------
   a   b  c   d   e
0  1  aa  3  22  aa
1  4  bb  5  11  bb
-------------------------
   a   b  c   d
0  1  aa  3  22
1  4  bb  5  11


In [55]:
V1=pd.DataFrame([[1,'aa',3],[4,'bb',5]],columns=list('abc')) #새로운 data의 생성
V2=pd.DataFrame([[11,'cc'],[22,'aa']],columns=list('db'))
print(V1)
print('-------------------------')
print(V2)

   a   b  c
0  1  aa  3
1  4  bb  5
-------------------------
    d   b
0  11  cc
1  22  aa


In [56]:
#공통된 열이 있을때의 옆으로 붙이기.: inner vs outer vs left
V3=pd.merge(V1,V2,how='inner')  #공통 열 ‘b’를 기준으로 교집합
print(V3)
print('-------------------------')
V4=pd.merge(V1,V2,how='outer')    #공통 열 ‘b’를 기준으로 합집합
print(V4)
print('-------------------------') 
V5=pd.merge(V1,V2,how='left')    #V1을 기준으로 ‘b’열에 있는 ID가 있는 V2의 행만 옆 붙이기
print(V5)

   a   b  c   d
0  1  aa  3  22
-------------------------
     a   b    c     d
0  1.0  aa  3.0  22.0
1  4.0  bb  5.0   NaN
2  NaN  cc  NaN  11.0
-------------------------
   a   b  c     d
0  1  aa  3  22.0
1  4  bb  5   NaN


In [57]:
rng=np.random.RandomState(1)
dset=pd.DataFrame({'ID':['A','B','C','A','B','C'],
                   'x1':range(6),
                   'x2':rng.randint(0,10,6)})  #DataFrame에서 dictionary 데이터의 key에 list데이터가 연결
print(dset)

  ID  x1  x2
0  A   0   5
1  B   1   8
2  C   2   9
3  A   3   5
4  B   4   0
5  C   5   0


In [58]:
print(dset.groupby('ID').mean())  #groupby( ) 함수의 이용
print('-------------------------')
print(dset.groupby('ID').std())

     x1   x2
ID          
A   1.5  5.0
B   2.5  4.0
C   3.5  4.5
-------------------------
         x1        x2
ID                   
A   2.12132  0.000000
B   2.12132  5.656854
C   2.12132  6.363961


In [59]:
#여러 가지 통계량 한번에 구하기
print(dset.groupby('ID').aggregate([min,max,np.mean,np.median,np.std]))

    x1                           x2                          
   min max mean median      std min max mean median       std
ID                                                           
A    0   3  1.5    1.5  2.12132   5   5  5.0    5.0  0.000000
B    1   4  2.5    2.5  2.12132   0   8  4.0    4.0  5.656854
C    2   5  3.5    3.5  2.12132   0   9  4.5    4.5  6.363961


In [60]:
#기초 통계량 구하기 
print(dset.groupby('ID')['x1'].describe()) #pandas의 describe()함수의 이용

    count  mean      std  min   25%  50%   75%  max
ID                                                 
A     2.0   1.5  2.12132  0.0  0.75  1.5  2.25  3.0
B     2.0   2.5  2.12132  1.0  1.75  2.5  3.25  4.0
C     2.0   3.5  2.12132  2.0  2.75  3.5  4.25  5.0


In [2]:
import pandas as pd
df=pd.DataFrame([[1,3,5],[2,4,6]],index=['a1','a2'], columns=['b1','b2','b3'])
df

b1  b2  b3
a1   1   3   5
a2   2   4   6

In [4]:
df.to_excel('C:/Users/YANG/Desktop/df1.xlsx',sheet_name='data')

In [5]:
df1=pd.read_excel('C:/Users/YANG/Desktop/df1.xlsx',sheet_name='data', index_col=0, header=0) 
# 열 이름과 INDEX 는 안불러옴
print(df1)
df2=pd.read_excel('C:/Users/YANG/Desktop/df1.xlsx',sheet_name='data', index_col=None, header=None)
print(df2)

    b1  b2  b3
a1   1   3   5
a2   2   4   6
     0   1   2   3
0  NaN  b1  b2  b3
1   a1   1   3   5
2   a2   2   4   6


In [6]:
df.to_csv('C:/Users/YANG/Desktop/out.csv')
df3=pd.read_csv('C:/Users/YANG/Desktop/out.csv', index_col=0, header=0)
print(df3)
df4=pd.read_csv('C:/Users/YANG/Desktop/out.csv',index_col=None, header=None)
print(df4)

    b1  b2  b3
a1   1   3   5
a2   2   4   6
     0   1   2   3
0  NaN  b1  b2  b3
1   a1   1   3   5
2   a2   2   4   6


In [22]:
df5=df3.reset_index(drop=True)
print(df5)
df6=df5.T.reset_index(drop=True).T
print(df6)
df7=df3.values  # 위와 같은 쓸데없는 짓 하지 말고 values만 호출하면 딱 나옴
print(df7)

   b1  b2  b3
0   1   3   5
1   2   4   6
   0  1  2
0  1  3  5
1  2  4  6
[[1 3 5]
 [2 4 6]]


In [7]:
text = open('C:/Users/YANG/Desktop/aa.txt','w')
text.close() # open 했으면 close꼭 써주기 (안하면 error엄청뜸)

In [8]:
# 생성된 파일에 데이터 작성하기
text = open('C:/Users/YANG/Desktop/aa.txt','w')
for i in range(10):
    data = ('player%d.\n' %i) # \n은 줄바꾸기 # d는 integer 이거를 row i에 할당함
    text.write(data)
text.close()

In [9]:
# file 한 줄씩 읽기
text = open('C:/Users/YANG/Desktop/aa.txt','r')
line = text.readline()
print(line)
text.close()

player0.



In [10]:
# 전체 파일 읽기
text = open('C:/Users/YANG/Desktop/aa.txt','r') # 옵션을 r로
data = text.read()
print(data)
text.close()

player0.
player1.
player2.
player3.
player4.
player5.
player6.
player7.
player8.
player9.



In [ ]:
# 기존 파일에 데이터 추가
text = open('C:/Users/YANG/Desktop/aa.txt','a') # 옵션을 a로
for i in range(10,12):
    data = ('player%d.\n' %i)
    text.write(data)
text.close()

In [16]:
# close자동으로 하기  -- 제대로 못적음
with open('C:/Users/YANG/Desktop/aa.txt','a')  as text:
    for i in range(12,16):
    data = ('writer%d.\n', %i)
text.close() 

IndentationError: expected an indented block (<ipython-input-16-6178dfa64526>, line 4)

In [ ]:
#### End of Padas chapter