In [ ]:
# =============================================================================
# ============================== 6. 넘파이(numpy) =============================
# =============================================================================

list, tuple, dictionary 다 numpy를 통해서만 manipulation이 가능하다 
pandas 또한 numpy를 back-end  즉 numpy위에 쌓아올린 패키지이다. 

class는 child 클래스와 parent 클래스가 있다.
class 안의 함수는 method라고 부른다. 

In [2]:
# numpy 불러와서 사용해보기
import numpy as np
np.array([1, 5, 7, 6])

array([1, 5, 7, 6])

np.array(list) 하면 1 dimensional tensor 데이터가 된거임
데이터 타입은 한 데이터 안에서 같아야 합니다 
밑에는 실수랑 정수가 섞여있어 run하면 자동 실수화 됩니다. 

In [3]:
np.array([1.25, 1, 5, 7])  # 실수와 정수가 섞여있으면 정수가 모두 실수화됨

array([1.25, 1.  , 5.  , 7.  ])

In [5]:
# numpy의 유용한 함수(방법)들
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.arange(0, 10, 2)   # 0 포함 O, 10 포함 X  # 0~9까지를 2씩 증가시켜

array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0, 10, 5)  # 0 포함 O, 10 포함 O  # 0~1사이를 "5개"로 나누어서 증가시킴

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.random.seed(12)

In [8]:
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [9]:
np.random.normal(0, 1, (3,3))  # 3 by 3 N(0,1) 생성

array([[-0.42069204, -0.7060276 ,  0.58535808],
       [ 0.13978644,  2.73781428,  1.11674795],
       [ 1.57453814, -0.08586679,  0.47673663]])

In [10]:
np.random.normal(1, 10, (3,3))  # 3 by 3 N(1,10) 생성

array([[-5.11386737, -2.49470943, -6.05416763],
       [-2.40186255, 21.27298707, -4.81080115],
       [ 9.73134844, 10.10565281, 11.47645612]])

In [18]:
np.random.randint(0, 10, (3,3)) # 3 by 3 정수(0-9) 생성

array([[6, 5, 9],
       [2, 4, 0],
       [8, 4, 4]])

In [15]:
rg = np.random.RandomState(40)  # np.random.RandomState 클래스를 rg로 객체화
rg.normal(0, 1, (3,3))

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [ ]:
## 추가설명 
numpy.random.RandomState(123) 

:  numpy.random.RandomState는 class명으로

랜덤넘버 생성기인 랜덤함수들을 포함하는 클래스라고 할 수 있다.

RandomState는 다양한 확률분포측면에 수 많은 랜덤넘버 생성기들을 가지고 있다.

ex) numpy.random.uniform(균등분포에서 변수 추출),

       numpy.random.nomal(정규분포에서 변수 추출), 등


rng = numpy.random.RandomState(123)과 같이 클래스 변수 rng를 선언 할 수 있습니다. 
이때 123은 일종의 번호로 randomstate 변수를 생성할 때 번호를 지정해서 넣어주지 않으면,
여러개의 randomstate 변수를 사용할 때 모두 같은 random한 값을 출력하게됩니다.
따라서 선언시에 각 변수 마다 다른 값을 넣음으로서 하나의 코드상에서 다른 랜덤한 값을 출력할 수 있게됩니다.



In [3]:
# array의 객체화
import numpy as np
np.random.seed(1)

x = np.random.randint(10, size=(2,3,4))  # 3x4 array를 2개 만들기
print(x);
print(x.ndim);
print(x.shape);
print(x.size);

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24


In [5]:
# array 접근과 편집(slicing)
x = np.array([0,3,5,2,4,6])  # 1차원
x[1]

3

In [10]:
x1=x[:,np.newaxis]
x1

array([[0],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [11]:
x2=x.reshape(6,1)
x2

array([[0],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [12]:
x3=np.reshape(x,(6,1))   # 둘다 결과는 똑같음
x3

array([[0],
       [3],
       [5],
       [2],
       [4],
       [6]])

x.reshape(6,1)
np.reshape(x,(6,1))

In [13]:
x4=x3.flatten()
x4

array([0, 3, 5, 2, 4, 6])

In [15]:
# 설명 추가
x = np.array([0,1,2,3,4]) # 1차원

x1 = x[:,np.newaxis]  # x의 열에 차원을 추가(1열 추가)
print(x1)
x1.shape

[[0]
 [1]
 [2]
 [3]
 [4]]


(5, 1)

In [16]:
x2 = x[np.newaxis,:] # x의 원 객체를 전치, 행에 차원을 추가
print(x2)
x2.shape

[[0 1 2 3 4]]


(1, 5)

In [17]:
x = np.array([0,1,2,3,4])
x[1:3] 

array([1, 2])

In [38]:
x[1:-2]   # 요소 개수는 총 5개 # x[1:5-2]과 동일

array([1, 2])

In [39]:
x[::2]    # x[start:stop:step]  # 맨 처음부터 끝까지 2개씩 건너뛰며 추출

array([0, 2, 4])

In [40]:
x[:2]  

array([0, 1])

In [41]:
x[::-1]   # 역순으로 

array([4, 3, 2, 1, 0])

In [18]:
x[5::-2]  # 5번째 요소부터 역으로 2칸씩 건너뛰며 추출

array([4, 2, 0])

In [22]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [3,4,2]])
x[:2, :2]  # 0,1번째 array요소 추출 후 각 요소들의 0,1번째 요소 추출 

array([[1, 2],
       [4, 5]])

In [23]:
x[1:4, :3] # 1,2,3 번째 array요소 추출 후 각 요소들의 0,1,2번째 요소 추출

array([[4, 5, 6],
       [7, 8, 9],
       [3, 4, 2]])

In [29]:
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  2]])

In [24]:
x[:, 0]   # 첫째 열

array([1, 4, 7, 3])

In [48]:
x[0, :]   # 첫째 행

array([1, 2, 3])

In [44]:
x[0]

array([1, 2, 3])

In [49]:
x[1, 2]   # list에서는 x[1][2]로 같은 동작을 수행하였음

6

In [27]:
x[0, 0] = 99
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  2]])

In [30]:
x1 = x[:2, :2]
x1

array([[99,  2],
       [ 4,  5]])

In [31]:
x1[0, 1] = 99
x1

array([[99, 99],
       [ 4,  5]])

In [32]:
print(x)  # subarray인 x1의 element를 수정하면 x에도 반영이 됨. ∵뷰 형태로 x와 동일한 객체를 참조

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  4  2]]


In [33]:
print(id(x));print(id(x1))    # 주소는 x와 다름

2467181429824
2467181458176


In [34]:
x1_copy = x[:2, :2].copy()
x1_copy[0, 0] = 1000  # x에 영향을 주지 않음
print(x)

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  4  2]]


In [ ]:
### 6.1 numpy의 차원 변경, 분할, 덧붙이기 ###

In [35]:
# 차원 변경
import numpy as np
x = np.array([1, 2, 3])
print(x)
x.reshape((1, 3))  # 2차원 행벡터화([]가 한 겹 더 생겼음)
print(x[np.newaxis, :]) 
x.reshape((3, 1))  # 2차원 열벡터화
print(x[:, np.newaxis]) 

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
# 추가
# 함수의 파라미터에 -1이 들어가면 특별한 의미를 갖는데, 다른 나머지 차원 크기를 맞추고 남은 크기를 해당 차원에 할당해 준다는 의미입니다

In [36]:
x = np.random.randint(10, size=(3,3,4)) # 3x4 행렬을 총 3개 만들기
print(x)
print('---------------------------')
x1 = x.reshape((3, 12))  # 3 by 4 행렬의 각 행을 옆으로 붙임
print(x1)

[[[9 9 7 6]
  [9 1 0 1]
  [8 8 3 9]]

 [[8 7 3 6]
  [5 1 9 3]
  [4 8 1 4]]

 [[0 3 9 2]
  [0 4 9 2]
  [7 7 9 8]]]
---------------------------
[[9 9 7 6 9 1 0 1 8 8 3 9]
 [8 7 3 6 5 1 9 3 4 8 1 4]
 [0 3 9 2 0 4 9 2 7 7 9 8]]


In [37]:
x2=x.reshape((-1,12))
print(np.shape(x2))
x.shape[1]  # x.shape 가 (3,3,4) 이므로

(3, 12)


3

In [38]:
# 분할
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [2,6]) # 2번째, 6번째에서 split
print(x1, x2, x3)
x1[0] = 100  # 분할된 변수의 변경은 x에 반영되지 않음
print(x1)
print(x)

[1 2] [3 4 5 6] [7 8]
[100   2]
[1, 2, 3, 4, 5, 6, 7, 8]


In [53]:
x = np.random.random((4, 4));print(x)

[[0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]
 [0.16983042 0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711 0.31551563]]


In [54]:
x1, x2 = np.vsplit(x, [2])  # 세로를 분할
print(x1)
print('--------------------------------------------------')
print(x2)

[[0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]]
--------------------------------------------------
[[0.16983042 0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711 0.31551563]]


In [55]:
y1, y2 = np.hsplit(x, [2])  # 가로를 분할
print(y1)
print('---------------------------')
print(y2)

[[0.80074457 0.96826158]
 [0.87638915 0.89460666]
 [0.16983042 0.8781425 ]
 [0.95788953 0.53316528]]
---------------------------
[[0.31342418 0.69232262]
 [0.08504421 0.03905478]
 [0.09834683 0.42110763]
 [0.69187711 0.31551563]]


In [7]:
# 덧붙이기
x = np.array([1, 2])
y = np.array([2, 3])
z = np.array([4, 5])
np.concatenate([x, y, z])

array([1, 2, 2, 3, 4, 5])

In [40]:
xx = np.array([[1,2,3], [4,5,6]])
yy = np.array([[2,4,6], [8,7,6]])
print(np.concatenate([xx, yy]))          # 아래로 붙임
print('---------------------------')
print(np.concatenate([xx, yy], axis=1))  # 옆으로 붙임

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
---------------------------
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [41]:
zz = np.array([55, 66, 77])
np.vstack([zz, xx])  # 세로로 쌓기. np.concatenate([zz.reshape((1,3)), xx])과 결과 동일

array([[55, 66, 77],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [42]:
ww = np.array([[100], [200]])  # 열벡터
np.hstack([ww, xx])  # 가로로 쌓기

array([[100,   1,   2,   3],
       [200,   4,   5,   6]])

In [ ]:
### 6.2 numpy 연산 ###

In [10]:
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x**3) # x의 3승
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [11]:
print(np.exp(x))
print(np.power(3, x)) # 3의 x승
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [12]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
M1 = M + 1
print(M1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [14]:
a = np.array([1, 2, 3])
M2 = M + a  # row by row로 연산 수행
print(M2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [43]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis] 
print(a);print(b)
print('---------------------------')
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
---------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size=(3,4))
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [17]:
print(np.sum(x))           # 원소의 총 합계
print(np.min(x, axis=1))   # 각 행의 최소값
print(np.mean(x, axis=0))  # 각 열의 평균
print(np.std(x, axis=0))   # 각 열의 표준편차

43
[0 2 2]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [18]:
x_std = (x - np.mean(x, axis=0))/np.std(x, axis=0)
print(np.sum(x_std, axis=0))

[ 4.44089210e-16  0.00000000e+00  1.11022302e-16 -7.77156117e-16]


In [45]:
### 6.2 논리 인덱싱(Boolean indexing)과 순서 정렬(Sorting) ###
import numpy as np
x = np.array([[1,2,3,10], [5,6,7,8]]); print(x)

[[ 1  2  3 10]
 [ 5  6  7  8]]


In [60]:
print(x >= 5) 
print(np.sum(x>=5)) 
# x가 5보다 큰것의 개수를 sum 
# x >= 5 자체가 논리식이므로 true나 false를 반환. true면 1, false는 0
print(np.sum(x>=5, axis=1))  # 각 행별로 5보다 큰 것의 개수

[[False False False  True]
 [ True  True  True  True]]
5
[1 4]


In [20]:
print(np.any(x>100))   # 어떤것이라도 100보다 큰게 있니? 즉 100보다 큰 숫자가 있는지 없는지 판단할때
print(np.all(x<7, axis=0))   # 각 열별로 연산
print(np.all(x==100)) # 모두 100이냐?

False
[ True  True False  True]
False


In [47]:
# 논리 인덱싱
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
y = np.array([1,0,1,0])
print(x[y==0, :])  # y=0인 행(1,3행) 과 모든 열 
print('---------------------------')
print(x[:, y==0])  # 모든 행과 y=0인 열

[[ 5  6  7  8]
 [13 14 15 16]]
---------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [48]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99]) 
ind1 = np.array([2, 3, 8])
ind2 = np.array([[2,1,3], [5,2,7]])

x1 = x[ind1] # [2,3,8]번째 행만 추출
x2 = x[ind2] # 첫번째 행은 [2,1,3]번째 꺼 / 두번째 행은 [5,2,7]번째 꺼 

print(x1)
print('---------------------------')
print(x2)

[33 44 99]
---------------------------
[[33 22 44]
 [66 33 88]]


In [50]:
# 인덱싱에서의 브로드캐스팅
x = np.arange(12).reshape((3,4)) # np.arange(12)는 0~11까지의 벡터를 만든것.
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print(y1[:,np.newaxis]) # 열벡터로 만들겠다는 뜻
print(y2)
print(x[y1, y2]) # [1,2] [2,0] [2,1] 번째 element
print('---------------------------')
print(x[y1[:,np.newaxis], y2]) # [1,2,2]번째 행을 먼저 추출하고, 그 행들의 [2,0,1]번째 element추출

[[1]
 [2]
 [2]]
[2 0 1]
[6 8 9]
---------------------------
[[ 6  4  5]
 [10  8  9]
 [10  8  9]]


In [26]:
# 순서 정렬
x = np.array([2, 4, 3, 1, 5])
print(np.sort(x))

[1 2 3 4 5]


In [27]:
ind = np.argsort(x) # sort한 것의 index
print(ind) 

[3 0 2 1 4]
